inputrc ========== *Plenty of new settings
bash_aliases
==========
*exported editor/visual and git to work correctly in gui software
*new aliases for rm and rmdir (to rmtrash)
*tree -C and pgrep -l

bash_functions
===========
*rework of old functions
*new notify to get popup from jobs
*alternateVBox changed default to save then pause

lxde keybindings
===========
*rework of alt+f4 for lxterminal
*new shortcut for pause/pause VB Spotify

New file settings.sh
====================
*Create script to set default autostart software
*Added libnotify and firefox_sync (without respawn) to autostart

vimrc
=======
*A bit of rework

vimperatorrc
==========
*Added cases

diff --git a/bash/bash_functions b/bash/bash_functions
--- a/bash/bash_functions
+++ b/bash/bash_functions
@@ -20,7 +20,7 @@
 ######################
 
 #Insert into dir stack checking repetitions
-_add_dir_stack () { 
+_add_dir_stack() { 
     local dir="$(realpath -P "${2:-"."}" 2>/dev/null)"
     [[ -d $dir ]] || { echo "Dir $dir not found";return;}
     # If executed _del_dir_stack and keep working in it...
@@ -55,7 +55,7 @@ _del_dir_stack () {
 }
 
 #Go to a dir stack number. 
-_go_dir_stack () { 
+_go_dir_stack() { 
     #Get absolute path
     local dir="$(dirs -l +$1 2>/dev/null)"
     [[ $dir ]] || { echo "Incorrect dir stack index or empty stack";return;}
@@ -66,19 +66,19 @@ _go_dir_stack () {
 # _go_dir_stack () { eval cd "~$1" && echo Changed dir to "${PWD}"; }
 
 #Show the dir stack below the bash prompt
-function _list_dir_stack {
-[ "${DIRSTACK_ENABLED}" != true ] && return
-_add_dir_stack false "$(pwd -P)"
-local i=0 
-local com="dirs -p"
-#Must use IFS= to not remove trailing whitespaces by process substitution
-while IFS= read -r line; do 
-    (( $i > 0 )) && echo -ne "\e[00;33m [\e[00m$i-$line\e[00;33m]\e[00m";
-    let i++
-done < <($com)
-if (( $i == 1 )); then 
-    echo -ne "\e[00;33mEmpty dir stack(a add,d delete,g go number,~num alias) \e[00m";
-fi
+_list_dir_stack() {
+    [ "${DIRSTACK_ENABLED}" != true ] && return
+    _add_dir_stack false "$(pwd -P)"
+    local i=0 
+    local com="dirs -p"
+    #Must use IFS= to not remove trailing whitespaces by process substitution
+    while IFS= read -r line; do 
+        (( $i > 0 )) && echo -ne "\e[00;33m [\e[00m$i-$line\e[00;33m]\e[00m";
+        let i++
+    done < <($com)
+    if (( $i == 1 )); then 
+        echo -ne "\e[00;33mEmpty dir stack(a add,d delete,g go number,~num alias) \e[00m";
+    fi
     #Use $'string' expansion to get a newline without new characters printed
     echo -n $'\n\r'
 }
@@ -98,146 +98,180 @@ fi
 ###########
 
 # Show the last command exit value in PROMPT_COMMAND 
-function _exitbash {
-    local last="$?" # Must come first
-    [ "${last}" -eq 0 ] && echo -ne "\e[01;38m" ||  echo -en "\e[01;31m"
+_exitbash() {
+    local last=$? # Must come first
+    (( $last == 0 )) && echo -ne "\e[01;38m" ||  echo -en "\e[01;31m"
     echo -en "($last)\e[00m "
 }
 
 
 #Show the size of something
 #maybe rework with tree or alike
-tam () { du -hs "$@" | sort -h; }
+tam() { du -hs "$@" | sort -h; }
 
 #############
 #  Desktop  #
 #############
 
-#Alternate between on/off states of a VM
-function alternateVBox {
-local machine="$1"
-local saved="$2"
-#Not Greedy state
-local regex='(State:)([[:space:]]*)([-[:alnum:][:space:]]*)([[:space:]].*)'
+notify(){
+    local title="${FUNCNAME[1]:-"Info message"}"
+    local text="${1:-"Info text"}"
+    local icon="${2:-"user-info"}"
+    local timeout=4
+     # zenity --timeout $timeout --info --title "$title" --text "$text"
+     notify-send -t $(($timeout*1000)) --icon="$icon" "$title" "$text" 
+}
 
-#Get the VM info
-readarray -t info <<< "$(VBoxManage showvminfo "$machine")" 
-#Search regex onto full array
-[[ ${info[@]} =~ ${regex} ]] || return 
+#Alternate between running/saved/paused/power off states of a VMVB
+alternateVBox() {
+    local machine="${1? $0 Needs a machine name}"
+    local pause="$2"
+    #Not Greedy state
+    local regex='(State:)([[:space:]]*)([-[:alnum:][:space:]]*)([[:space:]].*)'
 
-local state="${BASH_REMATCH[3]}"
-echo $machine State was:"\"$state\""
+    #Get the VM info
+    readarray -t info <<< "$(VBoxManage showvminfo "$machine" 2>/dev/null)" 
+    #Search regex onto full array
+    [[ ${info[@]} =~ ${regex} ]] || { echo "$machine not found"; return; }
 
-[ "$state" == "paused" ] && VBoxManage controlvm "$machine" resume 
-[[ "$state" = "saved" || "$state" = "powered off"  ]] && VBoxManage startvm "$machine" --type headless
+    local state="${BASH_REMATCH[3]}"
+    echo $machine State was:"\"$state\""
 
-if [ "$state" == "running" ]; then
-    [ "$saved" ] &&  VBoxManage controlvm "$machine" savestate && return
-    VBoxManage controlvm "$machine" pause
-fi
+    if [[ $state == "paused" ]]; then
+        VBoxManage controlvm "$machine" resume && \ 
+        notify  "$machine resumed!" virtualbox
+    fi
+
+    case $state in saved|"powered off") VBoxManage startvm "$machine" --type headless && \
+                notify  "$machine started!" virtualbox ;;
+    esac
+
+    if [[ $state == "running" ]]; then
+        if [[ $pause ]]; then
+            VBoxManage controlvm "$machine" pause && \
+                notify  "$machine paused!" virtualbox
+        else # Save state to hard disk
+            VBoxManage controlvm "$machine" savestate && \
+                notify  "$machine was saved!" virtualbox
+        fi
+    fi
 }
 
 
-#Download vid and play it in FS from bash or vimperator or whatever
-function descarga {
-local dest=~/Descargas/videoFlash
-local url="$1"
-killall -q youtube-dl
-cd ~ # youtube-dl doesn't get DEST right ¿?
-rm "$dest"
-#My temporal local latest version of youtube-dl for rtve
-[ -e "~/Scripts/youtube-dl" ] && wget https://yt-dl.org/latest/youtube-dl -O ~/Scripts/youtube-dl
-~/Scripts/youtube-dl "$url" --verbose -o "$dest" -f best --no-part >/tmp/youtube.log &
-sleep 4 
-mplayer -fs "$dest" 
+#Download a vid and play it in FS from bash or vimperator or whatever
+descarga() {
+    local latest=false
+    local dest=~/Descargas/videoFlash
+    local url="$1"
+    local options=" $url --add-metadata  --verbose -o $dest -f best --no-part "
+    killall -q youtube-dl
+    cd ~ # youtube-dl doesn't get DEST right ¿?
+    rm -f "$dest"
+    #Failback for latest youtube-dl in case of errors on fedora's one
+    if [[ $latest = true ]]; then
+        if [[ ! -x "~/Scripts/youtube-dl" ]]; then 
+            wget https://yt-dl.org/latest/youtube-dl -O ~/Scripts/youtube-dl
+            chmod +x ~/Scripts/youtube-dl
+        fi
+        ~/Scripts/youtube-dl $options >/tmp/youtube.log &
+    else
+        youtube-dl $options >/tmp/youtube.log &
+    fi
+    local downloading=$!
+    #maybe check file size otherwise going to sleep
+    sleep 4 
+    mplayer -fs "$dest" & 
+    #it'd be better get the metadata working on local file
+    local title="$(youtube-dl -e "$url")"
+    wait -n $downloading && notify "Video downloaded for $title!" smplayer
 }
 
 
 #Download and install the current extension pack for virtualbox 
-function virtualboxGetExtensionPack() {
-local version=$(VBoxManage --version)
-local ver=${version:0:6}
-local base="http://download.virtualbox.org/virtualbox"
-local pkg="Oracle_VM_VirtualBox_Extension_Pack-$ver-${version: -6}.vbox-extpack"
-local url="$base/$ver/$pkg"
-cd /tmp/
-wget "$url" || { echo "URL:$url not found"; return; }
-echo Downloaded /tmp/"$pkg" 
-VBoxManage extpack install /tmp/"$pkg"
-VBoxManage list extpacks
+virtualboxGetExtensionPack() {
+    local version=$(VBoxManage --version)
+    local ver=${version:0:6}
+    local base="http://download.virtualbox.org/virtualbox"
+    local pkg="Oracle_VM_VirtualBox_Extension_Pack-$ver-${version: -6}.vbox-extpack"
+    local url="$base/$ver/$pkg"
+    cd /tmp/
+    wget "$url" || { echo "URL:$url not found"; return; }
+    echo Downloaded /tmp/"$pkg" 
+    VBoxManage extpack install /tmp/"$pkg"
+    VBoxManage list extpacks
 }
 
 #Sync & set firefox profile between RAM and non-voltatile storage
-function firefox_sync() {
-hash rsync || { echo rsync must be installed!; return; }
-#Firefox home
-local firhome="$HOME/.mozilla/firefox"
-#Firefox default profile
-local profile=($firhome/*.default)
-#RAM directory 
-local volatile="/tmp/firefox-$USER"
-#My profile name
-local link=${profile##*/}
-local static=${link}.solid
+firefox_sync() {
+    hash rsync || { echo rsync must be installed!; return; }
+    #Firefox home
+    local firhome="$HOME/.mozilla/firefox"
+    #Firefox default profile
+    local profile=($firhome/*.default)
+    #RAM directory 
+    local volatile="/tmp/firefox-$USER"
+    #My profile name
+    local link=${profile##*/}
+    local static=${link}.solid
 
-#Changed to firefox home dir
-cd "$firhome"
+    #Changed to firefox home dir
+    cd "$firhome"
 
-#First run of the day
-[[ -d $volatile ]] || mkdir -m0700 "$volatile"
-[[ -e $link ]] || { echo $link must exist!. ; return; }
+    #First run of the day
+    [[ -d $volatile ]] || mkdir -m0700 "$volatile"
+    [[ -e $link ]] || { echo $link must exist!. ; return; }
 
-#if not already soft linked
-if [[ $(readlink $link) != $volatile ]]; then
-    files=($link/*)
-    #Move and make backup if not empty dir
-    if (( ${#files[@]} > 1 )); then
-        mv $link $static
-        local cache=${HOME}/.cache/mozilla/firefox/
-        [[ -d $cache ]] || mkdir -p "$cache"
-        tar zcfp ${cache}/firefox_profile_backup.tar.gz $static
+    #if not already soft linked
+    if [[ $(readlink $link) != $volatile ]]; then
+        files=($link/*)
+        #Move and make backup if not empty dir
+        if (( ${#files[@]} > 1 )); then
+            mv $link $static
+            local cache=${HOME}/.cache/mozilla/firefox/
+            [[ -d $cache ]] || mkdir -p "$cache"
+            tar zcfp ${cache}/firefox_profile_backup.tar.gz $static
+        fi
+        ln -s $volatile $link
     fi
-    ln -s $volatile $link
-fi
 
 
-if [[ -f $link/.unpacked ]]; then
-    rsync -a --delete --exclude .unpacked ./$link/ ./$static/
-else
-    rsync -a ./$static/ ./$link/
-    touch $link/.unpacked
-fi
+    if [[ -f $link/.unpacked ]]; then
+        rsync -a --delete --exclude .unpacked ./$link/ ./$static/
+    else
+        rsync -a ./$static/ ./$link/
+        touch $link/.unpacked
+    fi
 }
 
 #Listen to several radios
-function radios(){
-[ "$1" = "xfm" ] && mplayer http://mediasrv-sov.musicradio.com/XFMLondon
-[ "$1" = "virgin" ] && mplayer http://www.smgradio.com/core/audio/ogg/live.pls?service=vrbb
-[ "$1" = "capital" ] && mplayer http://mediasrv-the.musicradio.com/CapitalRadio
-[ "$1" = "bbcworld" ] && mplayer -playlist  http://bbc.co.uk/radio/worldservice/meta/tx/nb/live_infent_au_nb.asx
-[ "$1" = "bbc1" ] && mplayer -playlist  http://bbc.co.uk/radio/listen/live/r1.asx
-[ "$1" = "bbc1x" ] && mplayer -playlist  http://bbc.co.uk/radio/listen/live/r1x.asx
-[ "$1" = "bbc2" ] && mplayer -softvol -softvol-max 200 -playlist  http://bbc.co.uk/radio/listen/live/r2.asx
-[ "$1" = "bbc3" ] && mplayer -softvol -softvol-max 200 -playlist  http://bbc.co.uk/radio/listen/live/r3.asx
-[ "$1" = "bbc4" ] && mplayer -playlist  http://bbc.co.uk/radio/listen/live/r4.asx
-[ "$1" = "bbc5" ] && mplayer -playlist  http://bbc.co.uk/radio/listen/live/r5.asx
-[ "$1" = "bbc6" ] && mplayer -playlist  http://bbc.co.uk/radio/listen/live/r6.asx
-[ "$1" = "bbcman" ] && mplayer -playlist  http://bbc.co.uk/radio/listen/live/bbcmanchester.asx
-[ "$1" = "vaughan" ] && mplayer http://server01.streaming-pro.com:8012 
-[ "$1" = "radio3" ] && mplayer -cache 500 -playlist http://rtve.stream.flumotion.com/rtve/radio3.mp3.m3u
-[ "$1" = "folk-eu" ] && mplayer http://www.live365.com/play/wumb919fast
-[ "$1" = "folk" ] && mplayer -cache 500 -playlist http://public.wavepanel.net/3LACLKLS7UVKONE4/listen/m3u
-# alias folkradio_graba='mplayer -cache 500 http://www.live365.com/play/wumb919fast -ao pcm:file=radio.wav -vo null -vc null'
-#FRANCE
-[ "$1" = "nrj" ] && mplayer mms://vipnrj.yacast.fr/encodernrj
-[ "$1" = "rtl" ] && mplayer http://streaming.radio.rtl.fr/rtl-1-44-96
-[ "$1" = "rtl2" ] && mplayer http://streaming.radio.rtl.fr/rtl2-1-44-96
-[ "$1" = "europe2" ] && mplayer mms://vipmms9.yacast.fr/encodereurope2
-[ "$1" = "fip" ] && mplayer http://viphttp.yacast.net/V4/radiofrance/fip_hd.m3u
-[ "$1" = "franceculture" ] && mplayer http://viphttp.yacast.net/V4/radiofrance/franceculture_hd.m3u
-[ "$1" = "franceinter" ] && mplayer http://viphttp.yacast.net/V4/radiofrance/franceculture_hd.m3u
-[ "$1" = "lemouv" ] && mplayer http://viphttp.yacast.net/V4/radiofrance/lemouv_hd.m3u
-echo "Posibles opciones: xfm virgin capital bbcworld bbc1 bbc1x bbc2 bbc3 bbc4 bbc5 bbc6 vaughan radio3 folk-eu folk rtl rtl2 nostalgie europe2 (broken links galore) "
+radios(){
+    [ "$1" = "xfm" ] && mplayer http://mediasrv-sov.musicradio.com/XFMLondon
+    [ "$1" = "virgin" ] && mplayer http://www.smgradio.com/core/audio/ogg/live.pls?service=vrbb
+    [ "$1" = "capital" ] && mplayer http://mediasrv-the.musicradio.com/CapitalRadio
+    [ "$1" = "bbcworld" ] && mplayer -playlist  http://bbc.co.uk/radio/worldservice/meta/tx/nb/live_infent_au_nb.asx
+    [ "$1" = "bbc1" ] && mplayer -playlist  http://bbc.co.uk/radio/listen/live/r1.asx
+    [ "$1" = "bbc1x" ] && mplayer -playlist  http://bbc.co.uk/radio/listen/live/r1x.asx
+    [ "$1" = "bbc2" ] && mplayer -softvol -softvol-max 200 -playlist  http://bbc.co.uk/radio/listen/live/r2.asx
+    [ "$1" = "bbc3" ] && mplayer -softvol -softvol-max 200 -playlist  http://bbc.co.uk/radio/listen/live/r3.asx
+    [ "$1" = "bbc4" ] && mplayer -playlist  http://bbc.co.uk/radio/listen/live/r4.asx
+    [ "$1" = "bbc5" ] && mplayer -playlist  http://bbc.co.uk/radio/listen/live/r5.asx
+    [ "$1" = "bbc6" ] && mplayer -playlist  http://bbc.co.uk/radio/listen/live/r6.asx
+    [ "$1" = "bbcman" ] && mplayer -playlist  http://bbc.co.uk/radio/listen/live/bbcmanchester.asx
+    [ "$1" = "vaughan" ] && mplayer http://server01.streaming-pro.com:8012 
+    [ "$1" = "radio3" ] && mplayer -cache 500 -playlist http://rtve.stream.flumotion.com/rtve/radio3.mp3.m3u
+    [ "$1" = "folk-eu" ] && mplayer http://www.live365.com/play/wumb919fast
+    [ "$1" = "folk" ] && mplayer -cache 500 -playlist http://public.wavepanel.net/3LACLKLS7UVKONE4/listen/m3u
+    # alias folkradio_graba='mplayer -cache 500 http://www.live365.com/play/wumb919fast -ao pcm:file=radio.wav -vo null -vc null'
+    #FRANCE
+    [ "$1" = "nrj" ] && mplayer mms://vipnrj.yacast.fr/encodernrj
+    [ "$1" = "rtl" ] && mplayer http://streaming.radio.rtl.fr/rtl-1-44-96
+    [ "$1" = "rtl2" ] && mplayer http://streaming.radio.rtl.fr/rtl2-1-44-96
+    [ "$1" = "europe2" ] && mplayer mms://vipmms9.yacast.fr/encodereurope2
+    [ "$1" = "fip" ] && mplayer http://viphttp.yacast.net/V4/radiofrance/fip_hd.m3u
+    [ "$1" = "franceculture" ] && mplayer http://viphttp.yacast.net/V4/radiofrance/franceculture_hd.m3u
+    [ "$1" = "franceinter" ] && mplayer http://viphttp.yacast.net/V4/radiofrance/franceculture_hd.m3u
+    [ "$1" = "lemouv" ] && mplayer http://viphttp.yacast.net/V4/radiofrance/lemouv_hd.m3u
+    echo "Posibles opciones: xfm virgin capital bbcworld bbc1 bbc1x bbc2 bbc3 bbc4 bbc5 bbc6 vaughan radio3 folk-eu folk rtl rtl2 nostalgie europe2 (broken links galore) "
 }
 
 
diff --git a/bash/bashrc b/bash/bashrc
--- a/bash/bashrc
+++ b/bash/bashrc
@@ -35,8 +35,9 @@ shopt -s cmdhist
 shopt -s histappend
 # Regexp in bash prompt
 shopt -s extglob
-#Report expansion errors
-shopt -s failglob
+#Disable report expansion errors (lot of problems...)
+#like wget http://url or tab completition
+shopt -u failglob
 #Allow dot expansion by globbing
 shopt -s dotglob
 
@@ -60,15 +61,15 @@ stty -ixon -ixoff ixany
 # INTERNAL VARIABLES  #
 #######################
 
-PROMPT_COMMAND='_exitbash;_list_dir_stack'
-PS1='\[\e[01;34m\][\[\e[00m\]\[\e[01;32m\]\u$(__git_ps1 "(%s)")->\[\e[00m\]\[\e[01;34m\]\w]\n[C:\#]>\[\e[00m\] ' 
+PROMPT_COMMAND='_exitbash;_list_dir_stack;'
+PS1='\[\e[01;34m\][\[\e[00m\]\[\e[01;32m\]\H@\u$(__git_ps1 "(%s)")->\[\e[00m\]\[\e[01;34m\]\w]\n[C:\#]>>>\[\e[00m\] ' 
 
-#Default editor
-EDITOR=vim  
 HISTSIZE=50000
 HISTFILESIZE=50000
 #Maybe I should rework this to make it dinamic again...
 HISTFILE=~/.bash_historys/history_
+#Ignore from history dumb commands as duplicates and exits
+HISTIGNORE="&:exit"
 
 # to work properly with shopt -s extglob  (ls -d .*)
 GLOBIGNORE=.:..
@@ -80,6 +81,21 @@ DIRSTACK_LIMIT=5
 # Full paths to exclude from dir stack
 DIRSTACK_EXCLUDE="$HOME:/foobar"
 
+
+###################
+#  Stderr in red  #
+###################
+# exec 9>&2
+# exec 8> >(
+# while IFS= read -r line || [[ -n $line ]]; do
+#     echo -e "\[\e[00;31m\]${line}\[\e[00m\]"
+# done
+# )
+#
+# function undirect(){ exec 2>&9; }
+# function redirect(){ exec 2>&8; }
+# trap "redirect;" DEBUG
+# PROMPT_COMMAND+='undirect;'
 
 ########################
 #  EXPORTED VARIABLES  #
@@ -98,6 +114,12 @@ export LESS="-eIrMX"
 # make less more friendly for non-text input files, see lesspipe(1)
 [ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"
 
+#Default editor
+export VISUAL=vim
+export EDITOR="$VISUAL"
+export GIT_EDITOR=vim
+
+
 ###########
 #  Binds  #
 ###########
@@ -109,8 +131,8 @@ bind -m vi-insert "\C-n":menu-complete
 # ctrl l make clear the screen on vi mode
 bind -m vi-insert "\C-l":clear-screen
 
-#Para que autocomplete tambien !$,!*,!!,!cat ... despues de un space ... :)
-bind Space:magic-space
+#Autocomplete !$,!*,!!,!cat ... before de un space ... :)
+# bind Space:magic-space
 
 ###########
 #  Files  #
